["protostar.config"]
protostar_version = "0.2.1"

["protostar.project"]
libs_path = "lib"

["protostar.shared_command_configs"]
cairo_path = ["./lib/cairo_contracts/src", "src"]
target = ["./contracts"]

[profile.ci.protostar.shared_command_configs]
no_color=true

["protostar.contracts"]
basic_ship = [
    "./contracts/ships/basic_ship/basic_ship.cairo",
]
